source 'https://ruby.taobao.org/'

gem 'jekyll'
gem 'sass'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'stringex'
gem 'pygments.rb'
gem 'redcarpet', '~> 3.2', '>= 3.2.3'
gem 'rouge'
gem 'tzinfo', '1.2.3'
gem 'tzinfo-data', '1.2017.2'
gem 'jekyll-paginate', '1.1.0'